#!/bin/bash
modname=ixa-pipe-topic
#
# Find the path to this module
#
if
  [ -z ${MODROOT+x} ]
then
  # Find out path ourselves
  thisdir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"
else
  thisdir=$MODROOT/$modname
fi
scriptpath=${thisdir}/run
#
# Find the language
#
if
  [ -z "${NAFLANG+x}" ]
then
  naffile=`mktemp -t naf.XXXXXX`
  cat >$naffile
  NAFLANG=`cat $naffile | python ${thisdir}/langdetect.py` 
  export NAFLANG
  cat $naffile | $scriptpath
  result=$?
  rm $naffile
  exit $result
fi
#
# Generate properties file
#
tempdir=`mktemp -d -t jex.XXXXXX`
mkdir $tempdir/documents
mkdir $tempdir/results
cat $thisdir/default.prop \
    | sed 's|jex/resources|'${thisdir}'/jex/LANG/resources|g' \
    | sed 's|jex/result|'${tempdir}'/jex/result|g' \
    | sed 's|LANG|'${NAFLANG}'|g' \
    >$tempdir/conf.prop
#
# run the module
#
cd $thisdir
JARFILE=ixa-pipe-topic-1.0.3.jar
java -Xmx1000m -jar $thisdir/$JARFILE -p $tempdir/conf.prop
#
# remove the temporary files
#
rm -rf $tempdir
